version: 0.0
os: linux
files:
  - source: /
<<<<<<< HEAD
    destination:/var/www/html/codedeploy
=======
    destination: /var/www/html/
>>>>>>> parent of 8e43d33... appspec.yml
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

